server:
  port: 8099
spring:
  redis:
    host: localhost
    port: 6379
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
#     defaultZone: http://configUser:configPassword@localhost:8099/eureka
      defaultZone: http://localhost:8099/eureka


